// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as App$LearningReasonReact from "./App.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$LearningReasonReact.make(/* array */[])), "root");

export {
  
}
/*  Not a pure module */
